package com.example.manage.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AssignLogEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public AssignLogEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStaff_idIsNull() {
            addCriterion("staff_id is null");
            return (Criteria) this;
        }

        public Criteria andStaff_idIsNotNull() {
            addCriterion("staff_id is not null");
            return (Criteria) this;
        }

        public Criteria andStaff_idEqualTo(Long value) {
            addCriterion("staff_id =", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idNotEqualTo(Long value) {
            addCriterion("staff_id <>", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idGreaterThan(Long value) {
            addCriterion("staff_id >", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idGreaterThanOrEqualTo(Long value) {
            addCriterion("staff_id >=", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idLessThan(Long value) {
            addCriterion("staff_id <", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idLessThanOrEqualTo(Long value) {
            addCriterion("staff_id <=", value, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idIn(List<Long> values) {
            addCriterion("staff_id in", values, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idNotIn(List<Long> values) {
            addCriterion("staff_id not in", values, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idBetween(Long value1, Long value2) {
            addCriterion("staff_id between", value1, value2, "staff_id");
            return (Criteria) this;
        }

        public Criteria andStaff_idNotBetween(Long value1, Long value2) {
            addCriterion("staff_id not between", value1, value2, "staff_id");
            return (Criteria) this;
        }

        public Criteria andTrace_numIsNull() {
            addCriterion("trace_num is null");
            return (Criteria) this;
        }

        public Criteria andTrace_numIsNotNull() {
            addCriterion("trace_num is not null");
            return (Criteria) this;
        }

        public Criteria andTrace_numEqualTo(Integer value) {
            addCriterion("trace_num =", value, "trace_num");
            return (Criteria) this;
        }

        public Criteria andTrace_numNotEqualTo(Integer value) {
            addCriterion("trace_num <>", value, "trace_num");
            return (Criteria) this;
        }

        public Criteria andTrace_numGreaterThan(Integer value) {
            addCriterion("trace_num >", value, "trace_num");
            return (Criteria) this;
        }

        public Criteria andTrace_numGreaterThanOrEqualTo(Integer value) {
            addCriterion("trace_num >=", value, "trace_num");
            return (Criteria) this;
        }

        public Criteria andTrace_numLessThan(Integer value) {
            addCriterion("trace_num <", value, "trace_num");
            return (Criteria) this;
        }

        public Criteria andTrace_numLessThanOrEqualTo(Integer value) {
            addCriterion("trace_num <=", value, "trace_num");
            return (Criteria) this;
        }

        public Criteria andTrace_numIn(List<Integer> values) {
            addCriterion("trace_num in", values, "trace_num");
            return (Criteria) this;
        }

        public Criteria andTrace_numNotIn(List<Integer> values) {
            addCriterion("trace_num not in", values, "trace_num");
            return (Criteria) this;
        }

        public Criteria andTrace_numBetween(Integer value1, Integer value2) {
            addCriterion("trace_num between", value1, value2, "trace_num");
            return (Criteria) this;
        }

        public Criteria andTrace_numNotBetween(Integer value1, Integer value2) {
            addCriterion("trace_num not between", value1, value2, "trace_num");
            return (Criteria) this;
        }

        public Criteria andTrace_amtIsNull() {
            addCriterion("trace_amt is null");
            return (Criteria) this;
        }

        public Criteria andTrace_amtIsNotNull() {
            addCriterion("trace_amt is not null");
            return (Criteria) this;
        }

        public Criteria andTrace_amtEqualTo(BigDecimal value) {
            addCriterion("trace_amt =", value, "trace_amt");
            return (Criteria) this;
        }

        public Criteria andTrace_amtNotEqualTo(BigDecimal value) {
            addCriterion("trace_amt <>", value, "trace_amt");
            return (Criteria) this;
        }

        public Criteria andTrace_amtGreaterThan(BigDecimal value) {
            addCriterion("trace_amt >", value, "trace_amt");
            return (Criteria) this;
        }

        public Criteria andTrace_amtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("trace_amt >=", value, "trace_amt");
            return (Criteria) this;
        }

        public Criteria andTrace_amtLessThan(BigDecimal value) {
            addCriterion("trace_amt <", value, "trace_amt");
            return (Criteria) this;
        }

        public Criteria andTrace_amtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("trace_amt <=", value, "trace_amt");
            return (Criteria) this;
        }

        public Criteria andTrace_amtIn(List<BigDecimal> values) {
            addCriterion("trace_amt in", values, "trace_amt");
            return (Criteria) this;
        }

        public Criteria andTrace_amtNotIn(List<BigDecimal> values) {
            addCriterion("trace_amt not in", values, "trace_amt");
            return (Criteria) this;
        }

        public Criteria andTrace_amtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trace_amt between", value1, value2, "trace_amt");
            return (Criteria) this;
        }

        public Criteria andTrace_amtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trace_amt not between", value1, value2, "trace_amt");
            return (Criteria) this;
        }

        public Criteria andGmt_createIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmt_createIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmt_createEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmt_create");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table assign_log
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 30 20:10:20 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}