package com.example.manage.entity;

import java.math.BigDecimal;
import java.util.Date;

public class AssignLogEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assign_log.id
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assign_log.staff_id
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    private Long staff_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assign_log.trace_num
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    private Integer trace_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assign_log.trace_amt
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    private BigDecimal trace_amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assign_log.gmt_create
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    private Date gmt_create;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assign_log.id
     *
     * @return the value of assign_log.id
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assign_log.id
     *
     * @param id the value for assign_log.id
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assign_log.staff_id
     *
     * @return the value of assign_log.staff_id
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public Long getStaff_id() {
        return staff_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assign_log.staff_id
     *
     * @param staff_id the value for assign_log.staff_id
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public void setStaff_id(Long staff_id) {
        this.staff_id = staff_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assign_log.trace_num
     *
     * @return the value of assign_log.trace_num
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public Integer getTrace_num() {
        return trace_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assign_log.trace_num
     *
     * @param trace_num the value for assign_log.trace_num
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public void setTrace_num(Integer trace_num) {
        this.trace_num = trace_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assign_log.trace_amt
     *
     * @return the value of assign_log.trace_amt
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public BigDecimal getTrace_amt() {
        return trace_amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assign_log.trace_amt
     *
     * @param trace_amt the value for assign_log.trace_amt
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public void setTrace_amt(BigDecimal trace_amt) {
        this.trace_amt = trace_amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assign_log.gmt_create
     *
     * @return the value of assign_log.gmt_create
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public Date getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assign_log.gmt_create
     *
     * @param gmt_create the value for assign_log.gmt_create
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    public void setGmt_create(Date gmt_create) {
        this.gmt_create = gmt_create;
    }
}