package com.example.manage.mapper;

import com.example.manage.config.MybatisRepository;
import com.example.manage.entity.AssignLogEntity;
import com.example.manage.entity.AssignLogEntityExample;
import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
@MybatisRepository
public interface AssignLogEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    int countByExample(AssignLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    int deleteByExample(AssignLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    @Delete({
        "delete from assign_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    @Insert({
        "insert into assign_log (staff_id, trace_num, ",
        "trace_amt, gmt_create)",
        "values (#{staff_id,jdbcType=BIGINT}, #{trace_num,jdbcType=INTEGER}, ",
        "#{trace_amt,jdbcType=DECIMAL}, #{gmt_create,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(AssignLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    int insertSelective(AssignLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    List<AssignLogEntity> selectByExample(AssignLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    @Select({
        "select",
        "id, staff_id, trace_num, trace_amt, gmt_create",
        "from assign_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    AssignLogEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") AssignLogEntity record, @Param("example") AssignLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    int updateByExample(@Param("record") AssignLogEntity record, @Param("example") AssignLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    int updateByPrimaryKeySelective(AssignLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assign_log
     *
     * @mbggenerated Thu Nov 30 20:10:20 CST 2017
     */
    @Update({
        "update assign_log",
        "set staff_id = #{staff_id,jdbcType=BIGINT},",
          "trace_num = #{trace_num,jdbcType=INTEGER},",
          "trace_amt = #{trace_amt,jdbcType=DECIMAL},",
          "gmt_create = #{gmt_create,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(AssignLogEntity record);
}